version: 2
jobs:
       build:
                working_directory: ~/
                docker:
                        # specify the version you desire here
                        - image: circleci/android:api-26-alpha                   

                environment:
                        # Customize the JVM maximum heap limit
                        _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                        # JVM_OPTS: -Xmx3200m
                        TERM: dumb
                
                steps:
                       # checkout onto repo
                        - checkout
                       
                        # Download and cache dependencies
                        - restore_cache:
                                keys:
                                        - jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
                        # setup environment
                        - run:
                                name: Setup Environment
                                command: ./environmentSetup.sh

                        - run:
                                name: Download dependencies
                                command: ./gradlew androidDependencies
                        
                        - save_cache:
                                key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                                paths:
                                        - ~/.gradle
                                keys:
                                        - jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

       test:
                machine:
                        enabled: true
                working_directory: ~/
                steps:
                        - run:
                                name: "Run lint tests"
                                command: ./gradlew lint test
                        - run:
                                name: "Run tests"
                                command: ./gradlew test

                        - store_artifacts:
                                path: app/build/reports
                                destination: reports
                        
                        - store_test_results:
                                path: app/build/test-results

       deploy:
                machine:
                        enabled: true
                working_directory: ~/
                steps:
                        - run:
                                name: Deploy to Play Store
                                command: ./gradlew :app:publishApkRelease

# define work flows
workflows:
        version: 2
        build-test-and-deploy:
                jobs:
                        - build
                        - test:
                                requires:
                                        build
                        # will only deploy if on master and release branches
                        - deploy:
                                requires:
                                        test
                                filters:
                                        branches:
                                                only:
                                                        - master
                                                        - /^release-.*/
                                                ignore:
                                                        - /^dev-.*/
                                                        - /^develop-.*/
                                                        - develop
                                                        - /^feature-.*/
