version: 2
jobs:
       build:
                working_directory: ~/moviereel
                docker:
                        # specify the version you desire here
                        - image: circleci/android:api-26-alpha                   

                environment:
                        # Customize the JVM maximum heap limit
                        _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                        JVM_OPTS: -Xmx3200m
                        TERM: dumb
                
                steps:
                       # checkout onto repo
                        - checkout

                        - run:
                                name: Setup environment
                                command: ./scripts/circleci_env_setup.sh

                        # Download and cache dependencies
                        - restore_cache:
                                key: MovieReel-{{ checksum "build.gradle" }}-{{ .Branch }}
                                keys:
                                      - app-{{ checksum "app/build.gradle" }}

                        # download dependencies
                        - run:
                               name: Download dependencies
                               command: ./gradlew androidDependencies

                        - save_cache:
                                key: MovieReel-{{ checksum "build.gradle" }}-{{ .Branch }}
                                paths: ~/.gradle
                                keys:
                                      - app-{{ checksum "app/build.gradle" }}

                        - persist_to_workspace:
                                root: .
                                paths: .

       test:
                docker:
                      - image: circleci/android:api-26-alpha
                working_directory: ~/moviereel
                steps:
                       - attach_workspace:
                              at: .

                       - restore_cache:
                              key: MovieReel-{{ checksum "build.gradle" }}-{{ .Branch }}
                              keys:
                                      - app-{{ checksum "app/build.gradle" }}

                       - run:
                              name: "Run tests"
                              command: ./gradlew test

                       - store_artifacts:
                               path: ~/moviereel/app/build/reports/tests/
                               destination: /reports/

                       - store_test_results:
                               path: ~/moviereel/app/build/test-results/

                       - persist_to_workspace:
                               root: .
                               paths: .

       deployBeta:
                docker:
                      - image: circleci/android:api-26-alpha
                working_directory: ~/moviereel
                steps:
                       - attach_workspace:
                              at: .

                       - restore_cache:
                              key: MovieReel-{{ checksum "build.gradle" }}-{{ .Branch }}
                              keys:
                                      - app-{{ checksum "app/build.gradle" }}

                       - run:
                              name: Assemble APKs and distribute to Beta Testing
                              command: ./scripts/circleci_beta_setup.sh

                       - store_artifacts:
                               path: ~/moviereel/app/build/outputs/apk/
                               destination: /app/apks/

                       - deploy:
                               name: Deploy to Play Store
                               command: ./gradlew :app:publishApkRelease

       deployProd:
                docker:
                      - image: circleci/android:api-26-alpha
                working_directory: ~/moviereel
                steps:
                       - attach_workspace:
                              at: .

                       - restore_cache:
                              key: MovieReel-{{ checksum "build.gradle" }}-{{ .Branch }}
                              keys:
                                      - app-{{ checksum "app/build.gradle" }}

                       - run:
                                name: Deploy to Play Store
                                command: ./gradlew :app:publishApkRelease

                       - store_artifacts:
                               path: ~/moviereel/app/build/outputs/apk/release/
                               destination: /app/apks/

                       - store_artifacts:
                               path: ~/moviereel/app/build/outputs/mapping/
                               destination: /app/mapping/

# define work flows
workflows:
        version: 2
        build-test-and-deploy:
                jobs:
                        - build
                        - test:
                                requires:
                                        - build

                        - deployBeta:
                                requires:
                                        - test
                                filters:
                                        branches:
                                                only:
                                                        - develop
                                                ignore:
                                                        - /master.*/
                                                        - /^feature-.*/
                                                        - /^release-.*/
                                                        - /^bugfix-.*/
                                                        - /^hotfix-.*/

                        - deployProd:
                                requires:
                                        - test
                                filters:
                                        branches:
                                                only:
                                                        - master
                                                        - /^release-.*/
                                                ignore:
                                                        - /^dev-.*/
                                                        - /^develop-.*/
                                                        - develop
                                                        - /^feature-.*/
                                                        - /^bugfix-.*/
                                                        - /^hotfix-.*/
